"use client";
import {useEffect,useMemo,useState} from "react";
import {Plus,Trash2,CalendarDays,ShieldCheck} from "lucide-react";
import FinanceChart from "@/components/finance-chart";
import {type Transaction,money} from "@/lib/expense-data";
import {useLocalDemo,dollars,toCents} from "@/lib/planning-store";

type Account={id:string;name:string;kind:string;balance:number};
type Bill={id:string;name:string;category:string;amount:number;due:string;status:string};
const isObject=(v:unknown):v is Record<string,unknown>=>v!==null&&typeof v==="object";
const validAmount=(x:unknown)=>typeof x==="number"&&Number.isSafeInteger(x)&&x>=0&&x<=1e12;
const validString=(x:unknown)=>typeof x==="string"&&x.length>0&&x.length<121;
const isAccount=(v:unknown):v is Account=>isObject(v)&&validString(v.id)&&validString(v.name)&&validString(v.kind)&&validAmount(v.balance);
const isBill=(v:unknown):v is Bill=>isObject(v)&&validString(v.id)&&validString(v.name)&&validString(v.category)&&validAmount(v.amount)&&typeof v.due==="string"&&/^\d{4}-\d\d-\d\d$/.test(v.due)&&["scheduled","paid"].includes(String(v.status));
const sampleAccounts:Account[]=[{id:"ac1",name:"Example Checking",kind:"Checking",balance:425000},{id:"ac2",name:"Example Savings",kind:"Savings",balance:910000}];
const sampleBills:Bill[]=[{id:"bill1",name:"Example Utilities",category:"Utilities",amount:12000,due:"2026-10-15",status:"scheduled"},{id:"bill2",name:"Example Internet",category:"Utilities",amount:7200,due:"2026-10-21",status:"scheduled"}];
function shiftCalendarMonth(month:string,step:number){const [y,m]=month.split("-").map(Number);const d=new Date(Date.UTC(y,m-1+step,1));return d.toISOString().slice(0,7)}
function Header({title,desc}:{title:string;desc:string}){return <div className="pagehead"><div><span className="eyebrow">FINANCEHUB · DEVELOPMENT PREVIEW</span><h1>{title}</h1><p>{desc}</p></div></div>}
function DemoNote({children}:{children:React.ReactNode}){return <div className="notice"><ShieldCheck size={18}/>{children}</div>}
export function Accounts(){
 const {items,setItems}=useLocalDemo("financehub:demo-accounts:v11",sampleAccounts,isAccount);
 const [name,setName]=useState("");const [kind,setKind]=useState("Checking");const [balance,setBalance]=useState("");const [error,setError]=useState("");
 const sum=items.reduce((a,b)=>a+b.balance,0);
 function add(e:React.FormEvent){e.preventDefault();const n=toCents(balance);if(!name.trim()||!Number.isSafeInteger(n)){setError("Enter a name and a nonnegative balance.");return}setItems(v=>[...v,{id:crypto.randomUUID(),name:name.trim().slice(0,90),kind,balance:n}]);setName("");setBalance("");setError("")}
 return <section className="content expenses-page"><Header title="Accounts & Balances" desc="Manually recorded account balance snapshots. No bank connectivity or automatic reconciliation yet."/><DemoNote>Do not enter real financial information. Account snapshots are planning values, not automatically adjusted by Transactions.</DemoNote><div className="expense-stats"><article className="stat"><div className="stat-heading">Tracked asset balances</div><strong>{dollars(sum)}</strong></article><article className="stat"><div className="stat-heading">Tracked accounts</div><strong>{items.length}</strong></article></div><FinanceChart title="Account balances" subtitle="Manually entered account snapshots" points={items.map(x=>({label:x.name,value:x.balance}))}/><div className="panel expansion-panel"><h2>Add an account snapshot</h2><form className="expansion-form" onSubmit={add}><label>Account name<input value={name} maxLength={90} onChange={e=>setName(e.target.value)} required placeholder="e.g. Main checking"/></label><label>Type<select value={kind} onChange={e=>setKind(e.target.value)}>{["Checking","Savings","Cash","Brokerage","Other asset"].map(x=><option key={x}>{x}</option>)}</select></label><label>Balance ($)<input value={balance} onChange={e=>setBalance(e.target.value)} required inputMode="decimal" placeholder="0.00"/></label><button className="primary"><Plus size={15}/> Add account</button></form>{error&&<p role="alert" className="expansion-error">{error}</p>}</div><div className="panel expansion-panel"><h2>Accounts</h2><div className="expansion-list">{items.map(x=><div key={x.id} className="expansion-row"><span><strong>{x.name}</strong><small>{x.kind}</small></span><strong>{dollars(x.balance)}</strong><button aria-label={`Delete ${x.name}`} onClick={()=>{if(confirm(`Remove fictional account ${x.name}?`))setItems(v=>v.filter(y=>y.id!==x.id))}}><Trash2 size={16}/></button></div>)}</div></div></section>
}
export function Bills(){
 const {items,setItems}=useLocalDemo("financehub:demo-bills:v11",sampleBills,isBill);
 const [name,setName]=useState("");const [amount,setAmount]=useState("");const [due,setDue]=useState("2026-10-20");const [category,setCategory]=useState("Utilities");const [error,setError]=useState("");
 const outstanding=items.filter(b=>b.status==="scheduled").reduce((a,b)=>a+b.amount,0);
 function add(e:React.FormEvent){e.preventDefault();const cents=toCents(amount);if(!name.trim()||!Number.isSafeInteger(cents)||cents<=0||!/^\d{4}-\d{2}-\d{2}$/.test(due)){setError("Enter a name, positive amount and due date.");return}setItems(x=>[...x,{id:crypto.randomUUID(),name:name.trim().slice(0,90),amount:cents,due,category,status:"scheduled"}]);setName("");setAmount("");setError("")}
 return <section className="content expenses-page"><Header title="Bills & Payments" desc="Plan upcoming bills and track due dates without double-counting recorded expenses."/><DemoNote>Marking a bill paid changes its planning status only. It does not create a transaction.</DemoNote><div className="expense-stats"><article className="stat"><div className="stat-heading">Scheduled commitments</div><strong>{dollars(outstanding)}</strong></article><article className="stat"><div className="stat-heading">Unpaid bills</div><strong>{items.filter(x=>x.status==="scheduled").length}</strong></article></div><FinanceChart title="Outstanding bills" subtitle="Scheduled amounts by bill" points={items.filter(x=>x.status==="scheduled").map(x=>({label:x.name,value:x.amount}))}/><div className="panel expansion-panel"><h2>Add a scheduled bill</h2><form className="expansion-form" onSubmit={add}><label>Name<input value={name} onChange={e=>setName(e.target.value)} required maxLength={90}/></label><label>Amount ($)<input value={amount} onChange={e=>setAmount(e.target.value)} required inputMode="decimal"/></label><label>Due date<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{["Housing","Utilities","Insurance","Debt","Other"].map(x=><option key={x}>{x}</option>)}</select></label><button className="primary"><Plus size={15}/> Add bill</button></form>{error&&<p role="alert" className="expansion-error">{error}</p>}</div><div className="panel expansion-panel"><h2><CalendarDays size={17}/> Payment calendar</h2><div className="expansion-list">{[...items].sort((a,b)=>a.due.localeCompare(b.due)).map(x=><div key={x.id} className="expansion-row"><span><strong>{x.name}</strong><small>{x.due} · {x.category}</small></span><strong>{dollars(x.amount)}</strong><select aria-label={`Status for ${x.name}`} value={x.status} onChange={e=>setItems(v=>v.map(b=>b.id===x.id?{...b,status:e.target.value}:b))}><option value="scheduled">Scheduled</option><option value="paid">Paid</option></select><button aria-label={`Delete ${x.name}`} onClick={()=>setItems(v=>v.filter(y=>y.id!==x.id))}><Trash2 size={16}/></button></div>)}</div></div></section>
}
export function Income({entries}:{entries:Transaction[]}){
 const incomes=useMemo(()=>entries.filter(x=>x.type==="income").sort((a,b)=>b.date.localeCompare(a.date)),[entries]);
 const total=incomes.reduce((s,t)=>s+t.amountCents,0);const groups=Object.entries(incomes.reduce<Record<string,number>>((m,t)=>(m[t.category]=(m[t.category]||0)+t.amountCents,m),{})).sort((a,b)=>b[1]-a[1]);
 return <section className="content expenses-page"><Header title="Income & Paychecks" desc="Income analytics sourced directly from Transactions. No second income ledger."/><DemoNote>Add or edit paychecks in Transactions using the Income type. Gross salary and tax withholding are not inferred from net deposits.</DemoNote><div className="expense-stats"><article className="stat"><div className="stat-heading">Recorded income · all dates</div><strong>{money(total)}</strong></article><article className="stat"><div className="stat-heading">Income transactions</div><strong>{incomes.length}</strong></article></div><FinanceChart title="Income by category" subtitle="All recorded income transactions" points={groups.map(([label,value])=>({label,value}))}/><div className="panel expansion-panel"><h2>Income activity</h2><div className="expansion-list">{incomes.map(x=><div key={x.id} className="expansion-row"><span><strong>{x.description}</strong><small>{x.date} · {x.category}</small></span><strong>{money(x.amountCents)}</strong></div>)}{!incomes.length&&<p>No income transactions recorded.</p>}</div></div></section>
}
export function NoSpend({entries}:{entries:Transaction[]}){
 const [month,setMonth]=useState(()=>`${new Date().getFullYear()}-${String(new Date().getMonth()+1).padStart(2,"0")}`);const [includeEssential,setIncludeEssential]=useState(false);
 const essential=["Housing","Utilities","Healthcare","Groceries","Education"];
 const all=entries.filter(x=>x.type==="expense"&&x.date.startsWith(month)&& (includeEssential||!essential.includes(x.category)));
 const spentDays=new Set(all.map(x=>x.date));const [year,m]=month.split("-").map(Number);const count=new Date(year,m,0).getDate();const dates=Array.from({length:count},(_,i)=>`${month}-${String(i+1).padStart(2,"0")}`);const now=new Date();const today=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}-${String(now.getDate()).padStart(2,"0")}`;const noSpend=dates.filter(d=>d<=today&&!spentDays.has(d)).length;
 return <section className="content expenses-page"><Header title="No-Spend Tracker" desc="See which days have no recorded discretionary spending, based on Transactions."/><DemoNote>Days without recorded spending are not verified no-spend days. Future dates are excluded from the no-spend count. Both household members’ entries appear when included in Transactions.</DemoNote><div className="expansion-toolbar"><label>Reporting month<div className="month-picker"><button type="button" aria-label="Previous month" onClick={()=>setMonth(shiftCalendarMonth(month,-1))}>‹</button><select aria-label="Month name" value={m} onChange={e=>setMonth(`${year}-${String(e.target.value).padStart(2,"0")}`)}>{Array.from({length:12},(_,i)=><option key={i+1} value={i+1}>{new Date(Date.UTC(2024,i,1)).toLocaleString("en-US",{month:"long",timeZone:"UTC"})}</option>)}</select><select aria-label="Year" value={year} onChange={e=>setMonth(`${e.target.value}-${String(m).padStart(2,"0")}`)}>{Array.from({length:21},(_,i)=>2020+i).map(y=><option key={y}>{y}</option>)}</select><button type="button" aria-label="Next month" onClick={()=>setMonth(shiftCalendarMonth(month,1))}>›</button></div></label><label><input type="checkbox" checked={includeEssential} onChange={e=>setIncludeEssential(e.target.checked)}/> Count essential expenses too</label></div><div className="expense-stats"><article className="stat"><div className="stat-heading">No recorded spend</div><strong>{noSpend} days</strong></article><article className="stat"><div className="stat-heading">Days with expenses</div><strong>{spentDays.size}</strong></article></div><div className="panel expansion-panel"><h2>Monthly spending calendar</h2><div className="no-spend-grid">{dates.map(d=><div key={d} title={spentDays.has(d)?"Expense recorded":"No matching expense recorded"} className={`no-spend-cell ${spentDays.has(d)?"spent":"quiet"}`}><strong>{Number(d.slice(-2))}</strong><small>{spentDays.has(d)?"Spent":"No record"}</small></div>)}</div></div></section>
}
export function Reports({entries}:{entries:Transaction[]}){
 const [year,setYear]=useState("2026");const filtered=entries.filter(x=>x.date.startsWith(year));const inc=filtered.filter(x=>x.type==="income").reduce((s,x)=>s+x.amountCents,0);const exp=filtered.filter(x=>x.type==="expense").reduce((s,x)=>s+x.amountCents,0);const monthly=Array.from({length:12},(_,i)=>{const key=`${year}-${String(i+1).padStart(2,"0")}`;return {label:new Date(`${key}-01T00:00:00Z`).toLocaleDateString("en-US",{month:"short",timeZone:"UTC"}),value:filtered.filter(x=>x.type==="expense"&&x.date.startsWith(key)).reduce((s,x)=>s+x.amountCents,0)}});
 const csv=()=>{const rows=[["date","description","type","category","amount_usd"],...filtered.map(x=>[x.date,x.description,x.type,x.category,(x.amountCents/100).toFixed(2)])];const quote=(s:string)=>`"${s.replaceAll('"','""')}"`;const file=new Blob([rows.map(row=>row.map(quote).join(",")).join("\r\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(file);const a=document.createElement("a");a.href=url;a.download=`financehub-demo-report-${year}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),0)};
 return <section className="content expenses-page"><Header title="Reports & Analytics" desc="Yearly cash flow and spending trends sourced from the transaction ledger."/><DemoNote>CSV exports contain fictional development data. Calculations reflect only transactions entered in this browser.</DemoNote><div className="expansion-toolbar"><label>Reporting year <select value={year} onChange={e=>setYear(e.target.value)}>{Array.from(new Set([...entries.map(t=>t.date.slice(0,4)),"2026"])).sort().reverse().map(y=><option key={y}>{y}</option>)}</select></label><button className="secondary-btn" onClick={csv}>Export CSV</button></div><div className="expense-stats"><article className="stat"><div className="stat-heading">Income</div><strong>{money(inc)}</strong></article><article className="stat"><div className="stat-heading">Expenses</div><strong>{money(exp)}</strong></article><article className="stat"><div className="stat-heading">Net cash flow</div><strong>{money(inc-exp)}</strong></article></div><FinanceChart title="Monthly expenses" subtitle={`Monthly spending in ${year}`} points={monthly}/><div className="panel expansion-panel"><h2>Financial metrics</h2><div className="expansion-row"><span>Recorded savings rate (cash-flow proxy)</span><strong>{inc>0?`${Math.round((inc-exp)/inc*100)}%`:"N/A"}</strong></div><div className="expansion-row"><span>Transaction count</span><strong>{filtered.length}</strong></div></div></section>
}
export function NetWorth(){
 const {items:accounts}=useLocalDemo("financehub:demo-accounts:v11",sampleAccounts,isAccount);
 const [debt,setDebt]=useState(2180000);const [retire,setRetire]=useState(0);
 useEffect(()=>{try{const raw=localStorage.getItem("financehub:fictional-debts:v1");if(raw){const val=JSON.parse(raw);if(Array.isArray(val))setDebt(val.reduce((s:number,d:{balanceCents?:number})=>s+(Number.isSafeInteger(d.balanceCents)?Number(d.balanceCents):0),0))}}catch{}try{const raw=localStorage.getItem("financehub:demo-retirement:v1");if(raw){const val=JSON.parse(raw);if(Array.isArray(val))setRetire(val.reduce((s:number,d:{balanceCents?:number})=>s+(Number.isSafeInteger(d.balanceCents)?Number(d.balanceCents):0),0))}}catch{}},[]);
 const assets=accounts.reduce((s,a)=>s+a.balance,0)+retire;
 return <section className="content expenses-page"><Header title="Net Worth" desc="Estimated asset and liability snapshot based on selected demo modules."/><DemoNote>Approximate, not an audited net worth. Retirement accounts already listed in Accounts would be double-counted. Refresh this page after changing Debt or Retirement records.</DemoNote><div className="expense-stats"><article className="stat"><div className="stat-heading">Assets (accounts + retirement)</div><strong>{dollars(assets)}</strong></article><article className="stat"><div className="stat-heading">Liabilities (tracked debt)</div><strong>{dollars(debt)}</strong></article><article className="stat"><div className="stat-heading">Estimated net worth</div><strong>{dollars(assets-debt)}</strong></article></div><FinanceChart title="Asset allocation snapshot" subtitle="Assets from manually entered balances" points={[...accounts.map(a=>({label:a.name,value:a.balance})),{label:"Retirement",value:retire}]}/></section>
}
