"use client";
import { useState } from "react";
import { authClient } from "@/lib/auth-client";
export default function HouseholdAccess() {
 const {data:session,isPending}=authClient.useSession();
 const [email,setEmail]=useState(""); const [password,setPassword]=useState("");const [name,setName]=useState("");
 const [houseName,setHouseName]=useState("Our Household"); const [households,setHouseholds]=useState<{id:string;name:string;role:string}[]>([]);
 const [selected,setSelected]=useState("");const [members,setMembers]=useState<{role:string;user:{name:string;email:string}}[]>([]);
 const [inviteEmail,setInviteEmail]=useState("");const [inviteToken,setInviteToken]=useState(""); const [acceptToken,setAcceptToken]=useState("");const [message,setMessage]=useState("");
 async function api(url:string,body?:object){const r=await fetch(url,{method:body?"POST":"GET",credentials:"same-origin",headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined,cache:"no-store"});const data=await r.json();if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data;}
 async function load(){try{const d=await api('/api/households');setHouseholds(d.households);setMessage('Households loaded');}catch(e){setMessage(String(e));}}
 async function run(fn:()=>Promise<void>){try{setMessage('Working...');await fn();}catch(e){setMessage(e instanceof Error?e.message:'Request failed');}}
 if(isPending)return <div className="card">Checking session...</div>;
 return <section className="card" style={{padding:24,maxWidth:750}}><h2>Household Access (Development)</h2><p>Separate accounts, household membership and invitation testing. This is NOT a production release; the finance dashboard still uses local demo data.</p>
 {!session ? <div style={{display:'grid',gap:12,maxWidth:400}}><input aria-label="Name" placeholder="Full name" value={name} onChange={e=>setName(e.target.value)}/><input aria-label="Email" placeholder="Email" type="email" value={email} onChange={e=>setEmail(e.target.value)}/><input aria-label="Password" placeholder="Password (12+ characters)" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><div style={{display:'flex',gap:8}}><button onClick={()=>run(async()=>{const r=await authClient.signUp.email({email,password,name});if(r.error)throw new Error(r.error.message);setMessage('Account created');})}>Register</button><button onClick={()=>run(async()=>{const r=await authClient.signIn.email({email,password});if(r.error)throw new Error(r.error.message);setMessage('Signed in');})}>Sign in</button></div></div> : <div style={{display:'grid',gap:12}}><p>Signed in: <strong>{session.user.email}</strong></p><button onClick={()=>run(async()=>{await authClient.signOut();setHouseholds([]);setSelected('');})}>Sign out</button><hr/><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><input aria-label="Household name" value={houseName} onChange={e=>setHouseName(e.target.value)}/><button onClick={()=>run(async()=>{await api('/api/households',{name:houseName});await load();})}>Create household</button><button onClick={load}>Load households</button></div><select aria-label="Household" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose a household</option>{households.map(h=><option key={h.id} value={h.id}>{h.name} ({h.role})</option>)}</select>{selected&&<><button onClick={()=>run(async()=>{const d=await api(`/api/households/${selected}`);setMembers(d.members);setMessage('Members loaded');})}>View members</button>{members.map((m,i)=><p key={i}>{m.user.name} — {m.role} — {m.user.email}</p>)}<div style={{display:'flex',gap:8}}><input aria-label="Invite email" placeholder="Invite partner by email" value={inviteEmail} onChange={e=>setInviteEmail(e.target.value)}/><button onClick={()=>run(async()=>{const d=await api(`/api/households/${selected}/invitations`,{email:inviteEmail});setInviteToken(d.invitationToken);setMessage('Development invitation token generated. Share through a private channel.');})}>Generate invitation</button></div>{inviteToken&&<p style={{overflowWrap:'anywhere'}}>One-time invitation token: <code>{inviteToken}</code></p>}</>}<div style={{display:'flex',gap:8}}><input aria-label="Accept invitation token" placeholder="Received invitation token" value={acceptToken} onChange={e=>setAcceptToken(e.target.value)}/><button onClick={()=>run(async()=>{await api('/api/invitations/accept',{token:acceptToken});setAcceptToken('');await load();})}>Accept invitation</button></div></div>}
 <p role="status" aria-live="polite">{message}</p></section>;
}
