"use client";
import {useMemo,useState} from "react";
import {Repeat,Plus,Pencil,Trash2,X,ShieldCheck} from "lucide-react";
import {useLocalDemo,dollars,toCents} from "@/lib/planning-store";
import FinanceChart from "@/components/finance-chart";
type Subscription={id:string;name:string;category:string;cost:number;frequency:"Monthly"|"Quarterly"|"Yearly";nextDate:string;active:boolean};
const seed:Subscription[]=[{id:"demo-s1",name:"Example Streaming",category:"Entertainment",cost:1499,frequency:"Monthly",nextDate:"2026-11-01",active:true},{id:"demo-s2",name:"Example Cloud Storage",category:"Technology",cost:9999,frequency:"Yearly",nextDate:"2027-02-15",active:true},{id:"demo-s3",name:"Example Fitness",category:"Health",cost:2500,frequency:"Monthly",nextDate:"2026-10-20",active:false}];
const validate=(v:unknown):v is Subscription=>{if(!v||typeof v!=="object")return false;const x=v as Partial<Subscription>;return typeof x.id==="string"&&typeof x.name==="string"&&x.name.length<=90&&typeof x.category==="string"&&typeof x.cost==="number"&&Number.isSafeInteger(x.cost)&&x.cost>=0&&x.cost<=1e12&&["Monthly","Quarterly","Yearly"].includes(x.frequency||"")&&typeof x.nextDate==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(x.nextDate)&&typeof x.active==="boolean"};
const blank={name:"",category:"Entertainment",cost:"",frequency:"Monthly" as Subscription["frequency"],nextDate:"2026-11-01",active:true};
const monthly=(x:Subscription)=>x.cost/(x.frequency==="Monthly"?1:x.frequency==="Quarterly"?3:12);
export default function Subscriptions(){
 const {items,setItems}=useLocalDemo("financehub:demo-subscriptions:v1",seed,validate);
 const [open,setOpen]=useState(false),[editing,setEditing]=useState<string|null>(null),[form,setForm]=useState(blank),[error,setError]=useState(""),[filter,setFilter]=useState("All");
 const active=items.filter(x=>x.active);const total=useMemo(()=>Math.round(active.reduce((a,x)=>a+monthly(x),0)),[items]);
 const chart=useMemo(()=>Object.entries(active.reduce<Record<string,number>>((acc,x)=>{acc[x.category]=(acc[x.category]||0)+monthly(x);return acc},{})).map(([label,value])=>({label,value:Math.round(value)})),[items]);
 const edit=(x?:Subscription)=>{setEditing(x?.id||null);setForm(x?{name:x.name,category:x.category,cost:(x.cost/100).toFixed(2),frequency:x.frequency,nextDate:x.nextDate,active:x.active}:blank);setError("");setOpen(true)};
 const save=(e:React.FormEvent)=>{e.preventDefault();const cost=toCents(form.cost);if(!form.name.trim()||form.name.length>90||!Number.isSafeInteger(cost)||cost<0||!Number.isFinite(Date.parse(form.nextDate))){setError("Provide a name, valid charge, and renewal date.");return}const entry:Subscription={...form,name:form.name.trim(),id:editing||crypto.randomUUID(),cost};setItems(v=>editing?v.map(x=>x.id===editing?entry:x):[...v,entry]);setOpen(false)};
 const shown=items.filter(x=>filter==="All"||(filter==="Active"?x.active:!x.active));
 return <section className="content expenses-page"><div className="pagehead"><div><span className="eyebrow">RECURRING EXPENSES</span><h1>Subscriptions</h1><p>Monitor recurring services, renewal dates, annual costs, and subscription categories.</p></div><button className="primary add-button" onClick={()=>edit()}><Plus size={16}/> Add Subscription</button></div>
 <div className="notice"><ShieldCheck size={18}/> Fictional browser-only records. Renewal reminders and automatic billing detection are not enabled.</div>
 <div className="expense-stats subscription-summary"><article className="stat"><div className="stat-heading">Estimated monthly cost <Repeat size={17}/></div><strong>{dollars(total)}</strong></article><article className="stat"><div className="stat-heading">Estimated annual cost</div><strong>{dollars(total*12)}</strong></article><article className="stat"><div className="stat-heading">Active subscriptions</div><strong>{active.length}</strong></article></div>
 <FinanceChart title="Subscription Costs by Category" subtitle="Normalized monthly spending · active services only" points={chart}/>
 <article className="panel"><div className="panel-title"><div><h2>Subscription Directory</h2><p>Manage plans, billing frequency, and renewal dates</p></div></div><div className="subscriptions-controls"><label>Status <select aria-label="Filter subscription status" value={filter} onChange={e=>setFilter(e.target.value)}>{["All","Active","Inactive"].map(x=><option key={x}>{x}</option>)}</select></label></div><div className="table-scroll"><table className="expense-table subscription-table"><thead><tr><th>Service</th><th>Charge</th><th>Frequency</th><th>Next renewal</th><th>Status</th><th>Actions</th></tr></thead><tbody>{shown.map(x=><tr key={x.id}><td><span className="merchant"><strong>{x.name}</strong><small>{x.category}</small></span></td><td>{dollars(x.cost)}</td><td>{x.frequency}</td><td>{x.nextDate}</td><td>{x.active?"Active":"Inactive"}</td><td className="row-actions"><button aria-label={`Edit ${x.name}`} onClick={()=>edit(x)}><Pencil size={16}/></button><button aria-label={`Delete ${x.name}`} onClick={()=>{if(confirm(`Delete demo subscription ${x.name}?`))setItems(v=>v.filter(i=>i.id!==x.id))}}><Trash2 size={16}/></button></td></tr>)}</tbody></table>{!shown.length&&<p className="no-results">No subscriptions match this filter.</p>}</div><p className="planning-meta">Monthly and annual totals normalize recurring billing frequencies; annual estimate is based on rounded monthly total. No tax or price increases modeled.</p></article>
 {open&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><div className="modal-card" role="dialog" aria-modal="true" aria-labelledby="subscription-heading"><div className="modal-top"><h2 id="subscription-heading">{editing?"Edit":"Add"} subscription</h2><button aria-label="Close" onClick={()=>setOpen(false)}><X/></button></div><form className="expense-form" onSubmit={save}><label>Service name<input required maxLength={90} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{["Entertainment","Technology","Health","Education","Business","Utilities","Other"].map(x=><option key={x}>{x}</option>)}</select></label><div className="two-fields"><label>Charge amount ($)<input required min="0" type="number" step="0.01" value={form.cost} onChange={e=>setForm({...form,cost:e.target.value})}/></label><label>Billing frequency<select value={form.frequency} onChange={e=>setForm({...form,frequency:e.target.value as Subscription["frequency"]})}>{["Monthly","Quarterly","Yearly"].map(x=><option key={x}>{x}</option>)}</select></label></div><label>Next renewal<input required type="date" value={form.nextDate} onChange={e=>setForm({...form,nextDate:e.target.value})}/></label><label className="subscription-checkbox"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Active subscription</label>{error&&<p role="alert" className="form-error">{error}</p>}<div className="form-actions"><button type="button" className="secondary-btn" onClick={()=>setOpen(false)}>Cancel</button><button className="primary">Save subscription</button></div></form></div></div>}
 </section>
}
